---
manager_name: "The Unnamed Manager"
verbose:  false
editor:   "vim -O" #defaults to ENV['EDITOR']
colors:   false

path: "~"
output_path: "."
dirs:
  storage: caterings
  working: working
  archive: archive

templates:
  project:  templates/blank.yml.erb
  document: templates/document.tex.erb

## CAREFUL HERE
project_file_extension: .yml
use_git: false
latex:   pdflatex

defaults:
  tax: 0.19
  lang: de
  canceled: false

  messages:
    de:
      offer: 
        - Angebot
        - "hiermit möchten wir Ihnen für die gastronomische Betreuung Ihrer Veranstaltung am <%= @data[:event][:prettydate] %> folgendes Angebot unterbreiten:"
        - ""
      invoice: 
        - Rechnung
        - "wir bedanken uns für Ihren Auftrag für das Catering am <%= @data[:event][:prettydate] %> und erlauben uns ihnen folgende Rechnung zu stellen:"
        - "Wir bitten um eine Begleichung des Betrags innerhalb von 14 Tagen nach Erhalt der Rechnung."
      signature: Mit freundlichen Grüßen

...
