---
path: "~"
output_path: "."

dirs:
  storage: luigi_projects # where working and archive are placed
  working: working
  archive: archive

  templates: luigi_projects/templates


#templates: # TODO settings/templates is deprecated, instead autodiscover settings/dirs/templates
#  project:  templates/blank.yml.erb

## CAREFUL HERE
project_file_extension: .yml
use_git: false

defaults:
  messages:
    de:
      offer: 
        - Angebot
        - "hiermit möchten wir Ihnen für die gastronomische Betreuung Ihrer Veranstaltung am <%= @data[:event][:prettydate] %> folgendes Angebot unterbreiten:"
        - ""
      invoice: 
        - Rechnung
        - "wir bedanken uns für Ihren Auftrag für das Catering am <%= @data[:event][:prettydate] %> und erlauben uns ihnen folgende Rechnung zu stellen:"
        - "Wir bitten um eine Begleichung des Betrags innerhalb von 14 Tagen nach Erhalt der Rechnung."
      signature: Mit freundlichen Grüßen

...
